/* ═══════════ ZIP ═══════════ */
let DLK=null;
const DLI={tab2:{f:'lab-hello-spring.zip',t:'📦 Lab Hello Spring',s:['Descompacte em <strong>hello-spring/</strong>.','Abra no IntelliJ: File → Open → Trust.','Terminal (<kbd>Alt+F12</kbd>): <code>./mvnw spring-boot:run</code>.','Segundo terminal: <code>curl -i :8080/hello</code>.']},tab3:{f:'lab-hello-dotnet.zip',t:'📦 Lab Hello .NET',s:['Descompacte em <strong>HelloDotnetApi/</strong>.','<code>code .</code>; Terminal (<kbd>Ctrl+`</kbd>): <code>dotnet run</code>.','Segundo terminal: <code>curl -i :porta/hello</code>.']},tab4:{f:'loja-tab4-api-first.zip',t:'📦 Tab 4 — API-First',s:['<code>contracts/openapi.yaml</code> = resultado da Sala (validado com <code>-m false</code>).','<code>ata.md</code>, <code>docker-compose.prism.yml</code>, <code>testes-mock.http</code>, <code>loja-api.postman_collection.json</code>.','Terminal: <code>docker compose -f docker-compose.prism.yml up -d</code>.']},tab5:{f:'loja-tab5-bancos.zip',t:'📦 Tab 5 — Bancos',s:['Descompacte em <strong>loja-infra/</strong>.','Terminal: <code>docker compose up -d</code>.','Conecte com <code>docker exec -it</code> e use o Playground CRUD.']},tab6:{f:'loja-tab6-java.zip',t:'📦 Tab 6 — API Java (IntelliJ)',s:['Java completo: 4 módulos, TDD, migração, Docker, CI.']},tab7:{f:'loja-tab7-csharp.zip',t:'📦 Tab 7 — API C# (VS Code)',s:['C# completo: solução, DDD, TDD, migração, Docker, CI.']}, tab8:{f:'loja-tab8-contrato-contextos.zip',t:'📦 Tab 8 — Contrato Multi-Contextos',s:['<code>openapi-multicontexto.yaml</code> (tags por contexto), ADRs 009–012, testes curl por role.']}, tab9:{f:'loja-tab9-csharp-contextos.zip',t:'📦 Tab 9 — C# Multi-Contextos',s:['Solução modular: Shared.Kernel + módulos Catálogo/Pedidos/Clientes, HTTP síncrono, roles por contexto.']},complete:{f:'loja-projeto-completo.zip',t:'📦 Projeto Completo',s:['Descompacte em <strong>loja-projeto/</strong> e abra o <code>COMO_RODAR.md</code>.','Ordem: Sala → labs → bancos → mock → backend → testes → migração.']}};
function openDlModal(k){DLK=k;const i=DLI[k];document.getElementById('dl-modal-title').textContent=i.t;document.getElementById('dl-modal-body').innerHTML='<p class="text-sm text-muted mb-2"><strong>Como fazer funcionar após baixar:</strong></p><ol>'+i.s.map(x=>'<li>'+x+'</li>').join('')+'</ol>';document.getElementById('dl-modal').classList.add('active');}
function closeDlModal(){document.getElementById('dl-modal').classList.remove('active');}
function pageFiles(sc){const o={};document.querySelectorAll(sc+' [data-zip-path]').forEach(e=>o[e.dataset.zipPath]=e.textContent);return o;}
async function confirmDownload(){closeDlModal();if(!window.JSZip){showToast('❌ JSZip indisponível. Sirva a página via HTTP.','error');return;}showToast('📦 Gerando ZIP no navegador...','info'); const tabsNecessarias=(DLK==='complete')?['tab2','tab3','tab4','tab5','tab6','tab7','tab8','tab9']:(DLK&&DLK.startsWith('tab')?[DLK]:[]); for(const t of tabsNecessarias){try{await loadTab(t);}catch(e){showToast('❌ Falha ao carregar '+t+': '+e.message,'error');return;}} const z=new JSZip();const add=(o,base)=>Object.entries(o).forEach(([p,c])=>(base?z.folder(base).file(p,c):z.file(p,c)));
 if(DLK==='tab2'){add(pageFiles('#tab2'));}
 else if(DLK==='tab3'){add(pageFiles('#tab3'));}
 else if(DLK==='tab4'){add(pageFiles('#tab4'));z.file('contracts/openapi.yaml',currentContract());z.file('ata.md',ataContent());}
 else if(DLK==='tab5'){add(pageFiles('#tab5'));}
 else if(DLK==='tab6'){add(pageFiles('#tab6'));}
 else if(DLK==='tab7'){add(pageFiles('#tab7'));}
 else if(DLK==='tab8'){add(pageFiles('#tab8'));}
 else if(DLK==='tab9'){add(pageFiles('#tab9'));}
 else if(DLK==='complete'){add(pageFiles('#tab2'));add(pageFiles('#tab3'));add(pageFiles('#tab4'));z.file('contracts/openapi.yaml',currentContract());z.file('ata.md',ataContent());add(pageFiles('#tab5'),'infra');add(pageFiles('#tab6'),'java');add(pageFiles('#tab7'),'csharp');z.file('COMO_RODAR.md','# 🚀 COMO RODAR — Projeto Completo\n\nOrdem: Sala de Contrato → labs hello → bancos → mock → backend → testes → migração.\nTerminais: IntelliJ Alt+F12 · VS Code Ctrl+`.\n');}
 const b=await z.generateAsync({type:'blob'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=DLI[DLK].f;a.click();URL.revokeObjectURL(a.href);showToast('✅ ZIP gerado: '+DLI[DLK].f);}
